---
- name: Install podman
  ansible.builtin.apt:
    name:
      - podman
    state: present
    update_cache: true

- name: Create yugabyte group
  ansible.builtin.group:
    name: "{{ yb_group }}"
    system: true

- name: Create yugabyte user
  ansible.builtin.user:
    name: "{{ yb_user }}"
    group: "{{ yb_group }}"
    system: true
    shell: /usr/sbin/nologin
    home: "{{ yb_install_dir }}"
    create_home: false

- name: Create install directory
  ansible.builtin.file:
    path: "{{ yb_install_dir }}"
    state: directory
    owner: "{{ yb_user }}"
    group: "{{ yb_group }}"
    mode: "0755"
