FROM scratch

ARG YB_VERSION=2025.2.3.2
ARG YB_BUILD=b1
ARG YB_ARCH=linux-x86_64

ADD https://software.yugabyte.com/releases/${YB_VERSION}/yugabyte-${YB_VERSION}-${YB_BUILD}-${YB_ARCH}.tar.gz /tarball/yugabyte.tar.gz
