---
- name: Common prerequisites on all nodes
  hosts: all
  become: true
  vars:
    yb_allow_version_change: true
  roles:
    - common
    - node-exporter
    - yb-build

- name: Apply config to YB masters
  hosts: masters
  become: true
  vars:
    yb_allow_config_change: true
  roles:
    - yb-master

- name: Apply config to YB tservers
  hosts: tservers
  become: true
  vars:
    yb_allow_config_change: true
  roles:
    - yb-tserver

- name: Rolling restart
  ansible.builtin.import_playbook: restart.yml
