name: CI Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, nuc-rophy]
    env:
      LIBVIRT_DEFAULT_URI: qemu:///system

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible molecule

      - name: Run molecule test
        run: molecule test
        env:
          MOLECULE_SSH_PUB_KEY: ${{ secrets.MOLECULE_SSH_PUB_KEY }}
          MOLECULE_SSH_IDENTITY_FILE: ${{ secrets.MOLECULE_SSH_IDENTITY_FILE }}
          MOLECULE_YB_SHIPPER_REGISTRY: ${{ secrets.MOLECULE_YB_SHIPPER_REGISTRY }}
          MOLECULE_NODE_EXPORTER_REGISTRY: ${{ secrets.MOLECULE_NODE_EXPORTER_REGISTRY }}
